services:
  es:
    container_name: es
    image: docker.elastic.co/elasticsearch/elasticsearch:${ES_VERSION}
    environment:
      - node.name=es
      - cluster.name=docker-cluster
      - cluster.initial_master_nodes=es,es2
      - discovery.seed_hosts=es2
      - ingest.geoip.downloader.enabled=false
      - action.destructive_requires_name=false
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
    networks:
      - docker-network

  es2:
    container_name: es2
    image: docker.elastic.co/elasticsearch/elasticsearch:${ES_VERSION}
    environment:
      - node.name=es2
      - cluster.name=docker-cluster
      - cluster.initial_master_nodes=es,es2
      - discovery.seed_hosts=es
      - ingest.geoip.downloader.enabled=false
      - action.destructive_requires_name=false
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9201:9200"
    networks:
      - docker-network

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:${KIBANA_VERSION}
    ports:
      - "5601:5601"
    environment:
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - xpack.security.authc.http.enabled=false
      - xpack.security.authc.http.autoSchemesEnabled=false
      - xpack.security.authc.selector.enabled=false
      - elasticsearc.ssl.verificationMode=none
      - elasticsearc.ssl.alwaysPresentCertificate=false
      - elasticsearch.hosts=['http://es:9200']
    networks:
      - docker-network
    depends_on:
      - es

networks:
  docker-network:
