filebeat.inputs:
- type: stdin

# output.console:
#  pretty: true

output.elasticsearch:
  hosts: ["https://es01:9200"]
  username: "elastic" # the default username for connection
  password: "1234567"
  ssl.verification_mode: "none" # do not verify the incoming certificate from ES