services:

  otelcol:
    container_name: otelcol
    profiles: ["observability"]
    image: ${COLLECTOR_CONTRIB_IMAGE}
    restart: unless-stopped
    networks:
      - docker-network
    command: ["--config=/etc/otel-collector-config.yml", ""]
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"

networks:
  docker-network: